[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Darren Burns <darren.burns@fanduel.com>"]
edition = "2018"

[dependencies]
rayon = "1.0.3"
uuid = { version = "0.7", features = ["v4"] }
itertools = "*"
scan_fmt = "0.1.3"